const WHITE_PIECE_COLOR = 0xffffff;
const BLACK_PIECE_COLOR = 0x222222;
const WHITE_PIECE_HOVER_COLOR = 0xcccccc;
const BLACK_PIECE_HOVER_COLOR = 0x555555;
const WHITE_PIECE_SELECTED_COLOR = 0xffff00;
const BLACK_PIECE_SELECTED_COLOR = 0xffff00;

const HIGHLIGHT_BOX_COLOR = 0xeeee00;

const PIECE_COORDINATE_Z = -0.2;

const BOARD_SIZE = 8;
const TILE_SIZE = 1;
const TILE_DEPTH = 0.5;

export {
  BOARD_SIZE,
  TILE_SIZE,
  TILE_DEPTH,
  WHITE_PIECE_COLOR,
  BLACK_PIECE_COLOR,
  WHITE_PIECE_HOVER_COLOR,
  BLACK_PIECE_HOVER_COLOR,
  WHITE_PIECE_SELECTED_COLOR,
  BLACK_PIECE_SELECTED_COLOR,
  HIGHLIGHT_BOX_COLOR,
  PIECE_COORDINATE_Z,
}
